nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'

yarnPath: .yarn/releases/yarn-3.3.1.cjs

npmScopes:
  smatch-corp:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN:-}'

packageExtensions:
  "@nestjs/apollo@*":
    dependencies:
      "@apollo/gateway": "*"
  "@nestjs/graphql@*":
    dependencies:
      "ts-morph": "^16"
  "graphql-yoga@*":
    dependencies:
      "@types/node": "*"
  "ts-loader@*":
    dependencies:
      "webpack": "*"
  "apollo-server-express@*":
    dependencies:
      "webpack": "*"
      "express": "*"